# Generated by Django 4.2.5 on 2023-09-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_album_artist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title',)},
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='songs', to='catalog_app.album'),
        ),
    ]
