# Generated by Django 4.2.5 on 2023-09-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_alter_songalbum_track_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songalbum',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_app.album'),
        ),
        migrations.AlterField(
            model_name='songalbum',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog_app.song'),
        ),
    ]
